# Generated by Django 3.1.2 on 2021-04-28 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='./profile_pics/default.jpg', upload_to='profile_pics'),
        ),
    ]
